import { Grid, Button, Text, Title } from '@mantine/core'
import { Group, Image, Stack, Container } from '@mantine/core'
import useTranslation from 'next-translate/useTranslation'
import Head from 'next/head'
import Link from 'next/link'
import { trpc } from '../misc/trpc'
import { useEffect, useState } from 'react'

export default function Index() {
  const { t } = useTranslation('common')
  const paragraphs = t('homeParagraph').split('\n')

  return (
    <>
      <Head>
        <title>{t('home')}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container size={1400} p={40}>
        <Grid>
          <Grid.Col xl={4}>
            <Stack spacing='xl'>
              <Title size={56}>{t('inet')}</Title>
              <Text size={30}>
                {paragraphs.map((line, index) => (
                  <Text key={index}>{line}</Text>
                ))}
              </Text>
              <Group>
                <Button color='gray' variant='light' size='lg' radius='md'>
                  {t('findYourDevice')}
                </Button>
                <Link href='/compare'>
                  <Button color='gray' variant='light' size='lg' radius='md'>
                    {t('compare')}
                  </Button>
                </Link>
              </Group>
            </Stack>
          </Grid.Col>
          <Grid.Col xl={8}>
            {/* <Spline scene='https://prod.spline.design/6Bg4l7N6w0UWWQqk/scene.splinecode' /> */}
            {/* <Image
              src={'/images/commercial/iphone_gallery_4.png'}
              fit='contain'
              alt={'device'}
            /> */}
          </Grid.Col>
        </Grid>
      </Container>
    </>
  )
}
